name = "RichardsDAE"
uuid = "2d814a57-0f92-4708-bf26-52717958381a"
authors = ["Huite <huite.bootsma@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8.1"
LinearAlgebra = "1.11.0"
LinearSolve = "3.48.0"
Plots = "1.41.2"
Revise = "3.12.3"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
